# Generated by Django 4.1.3 on 2023-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/documentos'),
        ),
    ]
